### ISSUE TITLE
Linker error: library for freetype

### ISSUE THREAD

**Issue by matthewhammer** [cuplv/IC_Edit#1]
I get this error when I try to compile with cargo:
`note: ld: library not found for -lfreetype`
(This is the end. The actual error is much longer.)

I'm assuming that I'm missing the development version of some C library for fonts.  Do you know the best way to install this missing stuff on a mac?

**Comment by kyleheadley** [comment]
did you do 'brew install freetype' (and sdl2) from the Notes.txt? I should
write that into the readme to make it more clear now that this is public.

If you did, than we'd have to look deeper into the implementation of
piston, the library used for graphics

**Comment by matthewhammer** [comment]
I did both brew installs.  They do not seem to affect the error message.

This seems possibly related: http://stackoverflow.com/questions/18887445/does-freetype-comes-pre-installed-on-mac

Also, related to that discussion thread, did you install XCode on the laptop where you are building this?

**Comment by kyleheadley** [comment]
I did not install Xcode, and am using OS X 10.10.5. I don't remember having
any trouble with dependencies. I'll look back at the piston setup to see if
they had further instructions

**Comment by kyleheadley** [comment]
I believe that this was solved by using current and/or nightly builds of the rust compiler.
